image: "python:3.11"

before_script:
  #- cp /etc/gitlab-runner/certs/ca.crt /usr/local/share/ca-certificates/ca.crt
  #- update-ca-certificates
  - python3 --version
  #- pip install -r requirements.txt
  - pip install flake8
  - pip install pylint
  - pip install bandit

stages:
  - Static Analysis




static_analysis:
  stage: Static Analysis
  tags: ["dev","python"]
  allow_failure: true
  script:
  - flake8 --max-line-length=280 --ignore=W605,E275
  - pylint . --recursive=y --disable=W0613,C0115,E0401,R0911,R0912,R0913,R0915,R0903,W0201,R1702,W1401,R0902,R0914 --max-line-length=280